import React from 'react';
import {
  SiAmazonaws,
  SiCplusplus,
  SiDocker,
  SiFastapi,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGo,
  SiGrafana,
  SiHelm,
  SiKubernetes,
  SiLinux,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNvidia,
  SiNodedotjs,
  SiOpenai,
  SiOwasp,
  SiPortainer,
  SiPostgresql,
  SiPrometheus,
  SiReact,
  SiRedis,
  SiTypescript,
  SiUbuntu,
  SiVite,
} from 'react-icons/si';
import { IHighlightedProject } from '../../../types/portfolio';
import { siteProfile } from '../../../config/siteProfile';
import {
  nodewrightProjectDetailQuotes,
  projectDetailsQuotes,
  stateSightProjectDetailQuotes,
} from '../ProjectDetailsSlide/ProjectDetailsSlide.config';

export const useHighlightedProjectsData = (): {
  highlightedProjects: IHighlightedProject[];
} => {
  const highlightedProjects: IHighlightedProject[] = [
    {
      slideNumberImg: '/assets/portfolio/1.svg',
      projectTitle: 'KubeLens AI',
      projectStatus: 'Major project | Production-cluster diagnostics',
      projectDescription: `AI-assisted Kubernetes operations console for deterministic diagnostics, incident workflows, root-cause analysis, runbooks, safe remediation, telemetry, and controlled cluster actions. Built around a React/Vite UI, Go API, FastAPI predictor, Kubernetes integrations, Helm, Kustomize, Prometheus, Grafana, and Jaeger tracing.`,
      projectHighlights: [
        'Inventory across pods, nodes, deployments, services, RBAC, events, storage, config, alerts, and incidents.',
        'Controlled write actions for restart, scale, rollback, cordon, drain, and apply behind RBAC and global safety gates.',
        'Deterministic diagnostics engine with evidence, recommendations, incident timelines, postmortems, audit trails, and assistant workflows.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/kublens/overview.png',
      projectMobileImg: '/assets/portfolio/projects/kublens/incident.png',
      projectVisualType: 'screenshot',
      projectDetailsQuotes,
      projectDetailImages: [
        '/assets/portfolio/projects/kublens/incident.png',
        '/assets/portfolio/projects/kublens/remediation.png',
        '/assets/portfolio/projects/kublens/assistant.png',
        '/assets/portfolio/projects/kublens/overview.png',
      ],
      projectDetailTools: [
        'Kubernetes',
        'Helm',
        'Kustomize',
        'Prometheus',
        'Grafana',
        'Jaeger',
        'Go',
        'FastAPI',
        'React/Vite',
      ],
      liveLink: 'https://github.com/AnouarMohamed/KubLens-AI',
      githubLink: 'https://github.com/AnouarMohamed/KubLens-AI',
      projectTechnologies: [
        'React/Vite',
        'Go API',
        'FastAPI',
        'Kubernetes',
        'Helm',
        'Kustomize',
        'Prometheus',
        'Grafana',
        'Jaeger',
      ],

      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiReact key={1} className={'tech-icon'} />,
        <SiVite key={2} className={'tech-icon'} />,
        <SiGo key={3} className={'tech-icon'} />,
        <SiFastapi key={4} className={'tech-icon'} />,
        <SiKubernetes key={5} className={'tech-icon'} />,
        <SiHelm key={6} className={'tech-icon'} />,
        <SiPrometheus key={7} className={'tech-icon'} />,
        <SiGrafana key={8} className={'tech-icon'} />,
        <span
          key={9}
          className={'tech-icon-img jaeger-logo'}
          role={'img'}
          aria-label={'Jaeger'}
        />,
      ],
    },
    {
      slideNumberImg: '/assets/portfolio/2.svg',
      projectTitle: 'StateSight',
      projectStatus: 'Major project | In active development',
      projectDescription: `GitOps forensic platform for Kubernetes that compares desired state from Git with live cluster state, explains drift, groups findings into incidents, and recommends actions such as ignore, monitor, investigate, or reconcile. It is not a deployment controller; it is an evidence-first investigation console.`,
      projectHighlights: [
        'Go API with versioned routes, request IDs, health/readiness, basic metrics, and workspace-scoped RBAC boundaries.',
        'Redis-backed worker writes deterministic drift analysis to PostgreSQL, including Git/live provenance and managedFields ownership evidence.',
        'Current baseline covers resource presence, replicas, images, env entries, resource requests/limits, annotations, labels, and Service selectors.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/statesight/incident.png',
      projectMobileImg: '/assets/portfolio/projects/statesight/overview.png',
      projectVisualType: 'screenshot',
      projectDetailsQuotes: stateSightProjectDetailQuotes,
      projectDetailImages: [
        '/assets/portfolio/projects/statesight/incident.png',
        '/assets/portfolio/projects/statesight/applications.png',
        '/assets/portfolio/projects/statesight/overview.png',
      ],
      projectDetailTools: [
        'Kubernetes drift',
        'Git desired state',
        'Go API',
        'Redis worker',
        'PostgreSQL evidence',
        'React/Vite UI',
        'OIDC boundary',
      ],
      liveLink: 'https://github.com/AnouarMohamed/StateSight',
      githubLink: 'https://github.com/AnouarMohamed/StateSight',
      projectTechnologies: [
        'Go',
        'React',
        'TypeScript',
        'PostgreSQL',
        'Redis',
        'Docker Compose',
        'GitOps',
      ],

      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiGo key={1} className={'tech-icon'} />,
        <SiReact key={2} className={'tech-icon'} />,
        <SiTypescript key={3} className={'tech-icon'} />,
        <SiPostgresql key={4} className={'tech-icon'} />,
        <SiRedis key={5} className={'tech-icon'} />,
        <SiDocker key={6} className={'tech-icon'} />,
        <SiGit key={7} className={'tech-icon'} />,
        <SiKubernetes key={8} className={'tech-icon'} />,
      ],
    },
    {
      slideNumberImg: '/assets/portfolio/3.svg',
      projectTitle: 'Nodewright (formerly Skyhook)',
      projectStatus: 'Open-source contribution | NVIDIA Kubernetes operator',
      projectDescription:
        'Kubernetes-aware package manager and operator for safely modifying and maintaining host OS state declaratively across clusters. My resume tracks this as a major open-source contribution area of roughly 10K lines across fixes, workflows, tests, and stability work.',
      projectHighlights: [
        'Operator, CRD, Helm, and package lifecycle work for host-level changes in Kubernetes environments.',
        'Supports node selectors, interruption budgets, workload-aware updates, runtime-required taints, and resource management validation.',
        'Former Skyhook naming still appears in code, CRDs, Helm charts, and dashboards while the Nodewright rename rolls out.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/nodewright/overview.png',
      projectMobileImg: '/assets/portfolio/projects/nodewright/overview.png',
      projectVisualType: 'screenshot',
      projectDetailsQuotes: nodewrightProjectDetailQuotes,
      projectDetailImages: ['/assets/portfolio/projects/nodewright/overview.png'],
      projectDetailTools: [
        'NVIDIA',
        'Kubernetes Operator',
        'Helm',
        'CRDs',
        'Node OS packages',
        'Grafana metrics',
      ],
      githubLink: 'https://github.com/NVIDIA/nodewright',
      liveLink:
        'https://docs.nvidia.com/aicr/integrator-guide/components/nodewright/',
      projectTechnologies: [
        'Kubernetes',
        'Operator',
        'Helm',
        'CRDs',
        'Node lifecycle',
        'Grafana',
      ],
      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiNvidia key={1} className={'tech-icon'} />,
        <SiKubernetes key={2} className={'tech-icon'} />,
        <SiHelm key={3} className={'tech-icon'} />,
        <SiGo key={4} className={'tech-icon'} />,
        <SiGrafana key={5} className={'tech-icon'} />,
        <SiLinux key={6} className={'tech-icon'} />,
      ],
    },
    {
      slideNumberImg: '/assets/portfolio/4.svg',
      projectTitle: 'DockerSwarmLens',
      projectStatus: 'Owned project | Swarm operations console',
      projectDescription:
        'Production operations console for Docker Swarm clusters with live inventory, deterministic diagnostics, incident workflows, approvals, audit logs, assistant streaming, OIDC-aware auth paths, telemetry, and Grafana embedding support.',
      projectHighlights: [
        'Cluster-scoped APIs for nodes, stacks, services, tasks, networks, volumes, secrets, configs, diagnostics, incidents, actions, and audit.',
        'Write safety model with global gates, role-aware policy, dry-run modes, durable action runs, approval flow, and audit IDs.',
        'CI covers backend format/vet/test, frontend lint/typecheck/test/build, predictor tests, Docker smoke build, and GHCR release flow.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/typescript.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/typescript.svg',
      projectVisualType: 'icon',
      githubLink: 'https://github.com/AnouarMohamed/DockerSwarmLens',
      liveLink: 'https://github.com/AnouarMohamed/DockerSwarmLens',
      projectTechnologies: [
        'Docker Swarm',
        'Go',
        'TypeScript',
        'FastAPI',
        'PostgreSQL',
        'Grafana',
      ],
      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiDocker key={1} className={'tech-icon'} />,
        <SiGo key={2} className={'tech-icon'} />,
        <SiTypescript key={3} className={'tech-icon'} />,
        <SiFastapi key={4} className={'tech-icon'} />,
        <SiPostgresql key={5} className={'tech-icon'} />,
        <SiGrafana key={6} className={'tech-icon'} />,
        <SiOpenai key={7} className={'tech-icon'} />,
      ],
    },
    {
      projectTitle: 'PentestBoard',
      projectStatus: 'Owned project | Authorized security assessment workflow',
      projectDescription:
        'Go-based authorized web security assessment platform with a React TypeScript dashboard and C++ evidence-processing engine. It manages scope, targets, OWASP-style checklists, findings, evidence metadata, remediation tracking, activity logs, and report generation.',
      projectHighlights: [
        'Backend includes PostgreSQL wiring, migrations, health checks, secure cookie-session auth, project membership enforcement, and RBAC.',
        'Evidence engine analyzes uploaded evidence metadata through a C++ binary called by the Go backend.',
        'Safety boundary is explicit: no exploitation automation, credential attacks, destructive scanning, or public-target scanning by default.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/go.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/go.svg',
      projectVisualType: 'icon',
      githubLink: 'https://github.com/AnouarMohamed/PentestBoard',
      liveLink: 'https://github.com/AnouarMohamed/PentestBoard',
      projectTechnologies: [
        'Go',
        'React',
        'TypeScript',
        'PostgreSQL',
        'C++',
        'OWASP',
      ],
      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiGo key={1} className={'tech-icon'} />,
        <SiReact key={2} className={'tech-icon'} />,
        <SiTypescript key={3} className={'tech-icon'} />,
        <SiPostgresql key={4} className={'tech-icon'} />,
        <SiCplusplus key={5} className={'tech-icon'} />,
        <SiOwasp key={6} className={'tech-icon'} />,
      ],
    },
    {
      projectTitle: 'ITO DevSecOps Infrastructure',
      projectStatus: 'Internship work | Production infrastructure',
      projectDescription:
        'Production internship work administering VPS infrastructure and migrating roughly 6 application services to Docker Swarm with Portainer, Traefik, then Nginx. The archive you provided shows Swarm stacks, Traefik/Portainer deployment, service cleanup scripts, and deployment notes.',
      projectHighlights: [
        'Hardened CI/CD with tests, CodeQL, dependency scanning, API monitoring, and uptime supervision.',
        'Documented deployment procedures and reduced recurring manual pre-deployment checks by about 30%.',
        'Operational stack included Docker Swarm, Portainer agent/CE, Traefik v2.11, Nginx, Let’s Encrypt, rate limits, retries, compression, and redirects.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/docker.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/docker.svg',
      projectVisualType: 'icon',
      githubLink: siteProfile.githubUrl,
      liveLink: siteProfile.githubUrl,
      projectTechnologies: [
        'Docker Swarm',
        'Portainer',
        'Traefik',
        'Nginx',
        'CodeQL',
      ],

      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiDocker key={1} className={'tech-icon'} />,
        <SiNginx key={2} className={'tech-icon'} />,
        <SiGithubactions key={3} className={'tech-icon'} />,
        <SiPortainer key={4} className={'tech-icon'} />,
        <SiAmazonaws key={5} className={'tech-icon'} />,
        <SiLinux key={6} className={'tech-icon'} />,
      ],
    },
    {
      projectTitle: 'TCP Command Channel',
      projectStatus: 'Owned project | Secure command protocol in Go',
      projectDescription:
        'Production-grade TCP command channel written in Go. It uses TLS, token authentication, length-prefixed frames, allowlisted execution, a single active session model, heartbeat handling, output caps, command history, and newline-delimited JSON audit logs.',
      projectHighlights: [
        'Server owns authentication, session control, auditing, heartbeat management, and operator terminal flow.',
        'Client owns command execution, native info commands, persistent shell mode, reconnect logic, and output safety.',
        'Security validation covers wrong tokens, certificate rejection, encrypted tcpdump proof, tests, race detector, and coverage.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/go.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/go.svg',
      projectVisualType: 'icon',
      githubLink: 'https://github.com/AnouarMohamed/TCP',
      liveLink: 'https://github.com/AnouarMohamed/TCP',
      projectTechnologies: ['Go', 'TLS', 'TCP', 'NDJSON audit', 'Linux', 'Make'],
      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiGo key={1} className={'tech-icon'} />,
        <SiLinux key={2} className={'tech-icon'} />,
        <SiGit key={3} className={'tech-icon'} />,
        <SiGithub key={4} className={'tech-icon'} />,
      ],
    },
    {
      projectTitle: 'AWS/Zabbix Hybrid Monitoring',
      projectStatus: 'Owned project | Hybrid cloud monitoring lab',
      projectDescription:
        'Centralized hybrid monitoring infrastructure on AWS using Zabbix 7.0 LTS over Docker Compose. The lab monitors Linux and Windows Server infrastructure with VPC/security group setup, passive agent polling, real-time CPU/RAM/disk metrics, host availability, alerting, and dashboards.',
      projectHighlights: [
        'AWS architecture includes VPC, public subnet, Internet Gateway, security groups, Ubuntu Zabbix server, Ubuntu Linux client, and Windows Server client.',
        'Zabbix server runs containerized with MySQL and web UI, keeping the monitoring stack portable and isolated.',
        'Documented deployment, configuration, screenshots, troubleshooting, and agent setup for Linux and Windows.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/shell.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/shell.svg',
      projectVisualType: 'icon',
      githubLink: 'https://github.com/AnouarMohamed/AWS-Zabbix-Hybrid-Monitoring',
      liveLink: 'https://github.com/AnouarMohamed/AWS-Zabbix-Hybrid-Monitoring',
      projectTechnologies: [
        'AWS EC2/VPC',
        'Zabbix 7.0',
        'Docker Compose',
        'MySQL',
        'Ubuntu',
        'Windows Server',
      ],
      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiAmazonaws key={1} className={'tech-icon'} />,
        <SiDocker key={2} className={'tech-icon'} />,
        <SiMysql key={3} className={'tech-icon'} />,
        <SiUbuntu key={4} className={'tech-icon'} />,
        <SiLinux key={5} className={'tech-icon'} />,
      ],
    },
    {
      projectTitle: 'Mundiapolis Library',
      projectStatus: 'Owned project | Production university library platform',
      projectDescription: `Production-grade university library platform for students, faculty, and library staff. It supports catalog discovery, borrowing requests, renewals, reviews, admin approvals, circulation, fines, reminders, analytics, exports, CI, and deployment-ready packaging.`,
      projectHighlights: [
        'Built with Next.js 15 App Router, React 19, TypeScript, Drizzle ORM, PostgreSQL, and GitHub Actions.',
        'Covers student/faculty workflows, staff approval flows, circulation operations, fines, reminders, analytics, and exports.',
        'Production deployment is available at mundia-library.vercel.app with repo-backed documentation.',
      ],
      slideHeight: '100vh',
      projectImg: '/assets/portfolio/projects/icons/typescript.svg',
      projectMobileImg: '/assets/portfolio/projects/icons/typescript.svg',
      projectVisualType: 'icon',
      githubLink: 'https://github.com/AnouarMohamed/Mundia_library',
      liveLink: 'https://mundia-library.vercel.app',
      projectTechnologies: [
        'Next.js 15',
        'React 19',
        'TypeScript',
        'PostgreSQL',
        'CI',
      ],

      slideBgColor: '#0d1117',
      technologyIcons: [
        <SiTypescript key={1} className={'tech-icon'} />,
        <SiReact key={2} className={'tech-icon'} />,
        <SiNextdotjs key={3} className={'tech-icon'} />,
        <SiNodedotjs key={4} className={'tech-icon'} />,
        <SiPostgresql key={5} className={'tech-icon'} />,
        <SiGithubactions key={6} className={'tech-icon'} />,
      ],
    },
  ];
  return {
    highlightedProjects,
  };
};
